# See https://github.com/bxparks/EpoxyDuino for documentation about using
# EpoxyDuino to compile and run AUnit tests natively on Linux or MacOS.

APP_NAME := TwoButtonsUsingOneButtonConfigFast
ARDUINO_LIBS := EpoxyMockDigitalWriteFast AceButton
include ../../../EpoxyDuino/EpoxyDuino.mk
